Fix wereAddressesSpentFrom with empty addresses
iotaledger/hornet pull request #399
Opened 2020-04-21 16:37 UTC by viossat

# Description

Requesting `wereAddressesSpentFrom` with an empty `addresses` array leads to three issue:
- return a "No addresses provided" error, but an empty array should be valid (!= missing `addresses` parameter)
- return both the error and a result because a `return` statement is missing
- return `states` equals to `null` instead of `[]`

This PR fixes these issues.

### Actual result
```json
{
  "error": "No addresses provided"
}
{
  "states": null,
  "duration": 0
}
```

### Expected result
```json
{
  "states": [],
  "duration": 0
}
```

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Fix

# How Has This Been Tested?

Basic requests with or without addresses.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have tested my code extensively
- [x] I have selected the `develop` branch as the target branch

2020-04-22 10:17 UTC, IoTMOD requested changes
Thanks for your PR!
The missing `return` is indeed an issue and should get fixed :ok_hand:

2020-04-22 10:17 UTC, IoTMOD commented on plugins/webapi/spent.go
> +	if query.Addresses == nil {
Please revert this change, because an empty query is a bad request

2020-04-22 10:17 UTC, IoTMOD commented on plugins/webapi/spent.go
> +	result := WereAddressesSpentFromReturn{States: []bool{}}
Please revert this, too

2020-04-28 18:40 UTC, muXxer commented
Sorry Mathieu... not today :)
But the missing return got fixed in another PR, thanks for that! :+1:

2020-04-28 18:40 UTC, closed without merging