Added optional PoW method
iotaledger/hornet pull request #589
Opened 2020-08-04 17:37 UTC by IoTMOD

2020-08-05 15:13 UTC, muXxer requested changes

2020-08-05 15:13 UTC, muXxer commented on pkg/pow/pow.go
> +	lastInitTimestamp int64
Use time.Time

2020-08-05 15:13 UTC, muXxer commented on pkg/pow/pow.go
> +	if h.lastInitTimestamp+powsrvReinitCooldown.Nanoseconds() <= time.Now().UnixNano() {
Use time.Since

2020-08-05 15:13 UTC, muXxer commented on pkg/pow/pow.go
> +func NewHandler() (*Handler, error) {
Call it "New"

2020-08-05 15:13 UTC, muXxer commented on pkg/pow/pow.go
> +	var localPoWFunc pow.ProofOfWorkFunc
Create a pow plugin and init the Handler globally with:

```go
var (
	PLUGIN      = node.NewPlugin("PoW", node.Enabled, configure, run)
	log         *logger.Logger
	handler     *pow.Handler
	handlerOnce sync.Once
)


// Handler gets the pow Handler instance.
func Handler() *pow.Handler {
	handlerOnce.Do(func() {
		// init the pow handler with all possible settings
	})
	return handler
}
```

Then you can call `pow.Handler()` from all plugins that use it, and you can connect the shutdown event cleanly with its own priority.

2020-08-05 15:13 UTC, muXxer commented on pkg/pow/pow.go
> +func NewHandler() (*Handler, error) {
Why return an error if it can never happen?

2020-08-05 15:13 UTC, muXxer commented on pkg/pow/pow.go
> +	h.Lock()
Only one PoW request at a time would be possible with this.
Do we need a lock here?

2020-08-05 15:13 UTC, muXxer commented on plugins/coordinator/plugin.go
> +	powHandler, err = pow.NewHandler()
Use the proposed global PoW handler from the plugin.

2020-08-05 15:13 UTC, muXxer commented on plugins/spammer/plugin.go
> +	if powHandler, err = pow.NewHandler(); err != nil {
Use the proposed global PoW handler from the plugin.

2020-08-05 15:13 UTC, muXxer commented on plugins/spammer/plugin.go
> +	daemon.BackgroundWorker("Close PoW handler", func(shutdownSignal <-chan struct{}) {
This can be moved to the global PoW handler plugin.

2020-08-05 15:13 UTC, muXxer commented on plugins/webapi/pow.go
> +	powHandler, err := pow.NewHandler()
Use the proposed global PoW handler from the plugin.

2020-08-07 14:56 UTC, alexsporn commented on pkg/whiteflag/test/whiteflag_test.go
> +	hornet_pow "github.com/gohornet/hornet/plugins/pow"
plugin in a package? 🙈

2020-08-07 15:07 UTC, muXxer commented on pkg/whiteflag/test/whiteflag_test.go
> +	hornet_pow "github.com/gohornet/hornet/plugins/pow"
Fixed :carlos:

2020-08-07 15:07 UTC, alexsporn approved these changes

2020-08-07 15:20 UTC, muXxer approved these changes

2020-08-07 15:29 UTC, merged