WIP: Added local snapshots
iotaledger/hornet pull request #67
Opened 2019-12-18 01:20 UTC by muXxer

Still WIP

2020-01-06 11:28 UTC, luca-moser requested changes

2020-01-06 11:28 UTC, luca-moser commented on packages/model/tangle/spent_db.go
> +	spentAddressesDatabaseTransactionLock sync.RWMutex
This lock isn't used anywhere. When generating the local snapshot file, the spent addresses count might not match the initial read count and therefore fail, as the spent addresses db wasn't locked.

2020-01-06 11:28 UTC, luca-moser commented on plugins/snapshot/globalSnapshot.go
> +	for err == nil {
Can replaced with a simple for {} as everytime an error occurs the loop is broken out of.

2020-01-06 11:28 UTC, luca-moser commented on plugins/snapshot/globalSnapshot.go
> +	for err == nil {
Same as above, err is always nil

2020-01-06 11:28 UTC, luca-moser commented on plugins/snapshot/globalSnapshot.go
> +		err = trinary.ValidTrytes(address)
combine into one `if err := ...; err != nil {}`

2020-01-06 11:28 UTC, luca-moser commented on plugins/snapshot/globalSnapshot.go
> +		err = trinary.ValidTrytes(address)
combine into one `if err := ...; err != nil {}`

2020-01-06 11:28 UTC, luca-moser commented on plugins/snapshot/globalSnapshot.go
> +		err := loadSpentAddresses(spent)
combine into one `if err := ...; err != nil {}`

2020-01-06 11:28 UTC, luca-moser commented on plugins/snapshot/localSnapshot.go
> +package snapshot
rename this file to `local_snapshot.go` or whatever else lowercased.

2020-01-06 11:28 UTC, luca-moser commented on plugins/snapshot/localSnapshot.go
> +		// HINT: Check for orphaned Tx as solid entry points is skipped in HORNET, since this operation is heavy and not necessary
Emphasize why checking for orphans is not necessary.

2020-01-06 11:28 UTC, luca-moser commented on plugins/snapshot/localSnapshot.go
> +// isSolidEntryPoint checks if the approvers of every approvee of that milestone were confirmed by later milestones
```suggestion
// isSolidEntryPoint checks whether any direct approver of the given transaction was confirmed by a milestone which is above the target milestone.
```

2020-01-06 11:28 UTC, luca-moser commented on plugins/snapshot/localSnapshot.go
> +func getApprovees(milestoneIndex milestone_index.MilestoneIndex, milestoneTail *hornet.Transaction) []trinary.Hash {
Rename to `getMilestoneApprovees()`, as otherwise it is ambiguous what approvees this gives given the name.

2020-01-06 11:28 UTC, luca-moser commented on plugins/snapshot/localSnapshot.go
> +func checkSnapshotNeeded(solidMilestoneIndex milestone_index.MilestoneIndex) {
Should be renamed to `shouldTakeSnapshot(...) bool` and move the `createLocalSnapshotWithoutLocking()` to the caller.

2020-01-06 11:28 UTC, luca-moser commented on plugins/snapshot/localSnapshot.go
> +	//		 When local snapshots were introduced in IRI, there was the problem that COO choose really old tx as valid tips, which is not the case anymore.
```suggestion
	//		 When local snapshots were introduced in IRI, there was the problem that COO approved really old tx as valid tips, which is not the case anymore.
```

2020-01-06 11:28 UTC, luca-moser commented on plugins/snapshot/localSnapshot.go
> +			// confirmed by a later milestone than tagetIndex => solidEntryPoint
```suggestion
			// confirmed by a later milestone than targetIndex => solidEntryPoint
```

2020-01-06 11:28 UTC, luca-moser commented on plugins/snapshot/localSnapshot.go
> +func getNewBalances(balances map[trinary.Hash]uint64, targetIndex milestone_index.MilestoneIndex, solidMilestoneIndex milestone_index.MilestoneIndex) map[trinary.Hash]uint64 {
Rename to `getLedgerStateAtMilestone()` or `rollbackLedgerState()`

2020-01-06 11:28 UTC, luca-moser commented on plugins/snapshot/localSnapshot.go
> +	for milestoneIndex := solidMilestoneIndex; milestoneIndex >= targetIndex; milestoneIndex-- {
The way this `for` is written, it also removes the diff generated by the given `targetIndex`, leading our `balances` to actually represent the state of `targetIndex` - 1.

2020-01-06 11:28 UTC, luca-moser commented on plugins/snapshot/localSnapshot.go
> +	err := checkSnapshotLimits(targetIndex)
combine into one `if err := ...; err != nil {}`

2020-01-06 11:28 UTC, luca-moser commented on plugins/snapshot/localSnapshot.go
> +	spentAddressesCount, err := tangle.CountSpentAddressesEntries()
You should lock the spent addresses database during snapshot creation, as otherwise this count can desync and lead `StreamSpentAddressesToWriter()` to return an error.

2020-01-06 11:28 UTC, luca-moser commented on plugins/snapshot/localSnapshot.go
> +	err = tangle.StreamSpentAddressesToWriter(gzipWriter, spentAddressesCount)
combine into one `if err := ...; err != nil {}`

2020-01-06 11:28 UTC, luca-moser commented on plugins/snapshot/localSnapshot.go
> +	err = lsh.WriteToBuffer(gzipWriter)
combine into one `if err := ...; err != nil {}`

2020-01-06 11:28 UTC, luca-moser commented on plugins/snapshot/localSnapshot.go
> +	os.Rename(filePathTmp, filePath)
Handle the rename error.

2020-01-06 11:28 UTC, luca-moser commented on plugins/snapshot/localSnapshot.go
> +	log.Info("Importing current ledger")
```suggestion
	log.Info("Importing ledger state")
```

2020-01-06 11:28 UTC, luca-moser commented on plugins/snapshot/parameters.go
> +	// "Amount of seen milestones to record in the local snapshot file"
```suggestion
	// "The depth, respectively the starting point, at which a local snapshot of the ledger is generated."
```

2020-01-06 11:28 UTC, luca-moser commented on plugins/snapshot/parameters.go
> +	// "Load global snapshot"
```suggestion
	// "Whether to load a global snapshot from provided text files."
```

2020-01-06 11:28 UTC, luca-moser commented on plugins/snapshot/parameters.go
> +	// "Delete old transactions from database"
```suggestion
	// "Whether to delete old transaction data from the database."
```

2020-01-06 11:28 UTC, luca-moser commented on plugins/snapshot/pruning.go
> +	tangle.DeleteBundlesInDatabase(bundles)
This also potentially deletes bundles where a reattachment of a very old bundle in the more present part was confirmed/alive, which can lead to random bugs. We should make sure that the bundle bucket doesn't reference any transaction in such fashion.

2020-01-08 09:33 UTC, luca-moser requested changes

2020-01-08 09:33 UTC, luca-moser commented on packages/model/hornet/solid_entry_points.go
> +	s.entryPointsMap[transactionHash] = milestoneIndex
I believe Add() should check whether the `transactionHash` is already in the `entryPointsMap` and then not potentially add a duplicate item to `entryPointsSlice`

2020-01-08 09:33 UTC, luca-moser commented on packages/model/hornet/solid_entry_points.go
>  func (s *SolidEntryPoints) Hashes() []trinary.Hash {
Kinda believe that Hashes() should return a copy of the slice instead of the original one, just so we don't accidentally modify it somewhere else.

2020-01-08 09:33 UTC, luca-moser commented on packages/model/tangle/bundle.go
> +			// check if the txs of this bundle are used in another bundle instance
We can short-circuit this if `bundleTxHash == txHash` and immediately add it to `txsToRemove` without having to check whether the tail transaction can occur in any other bundle instance (it can't).

2020-01-08 09:33 UTC, luca-moser commented on packages/model/tangle/ledger_db.go
> +// GetLedgerDiffForMilestoneWithoutLocking returns the ledger changes of that specific milestone
```suggestion
// GetLedgerDiffForMilestoneWithoutLocking returns the ledger changes of that specific milestone.
```

2020-01-08 09:33 UTC, luca-moser commented on packages/model/tangle/ledger_db.go
> +// ReadLockLedger must be held while entering this function
```suggestion
// ReadLockLedger must be held while entering this function.
```

2020-01-08 09:33 UTC, luca-moser commented on packages/model/tangle/spent_db.go
> +// CountSpentAddressesEntries returns the amount of spent addresses
```suggestion
// CountSpentAddressesEntries returns the amount of spent addresses.
```

2020-01-08 09:33 UTC, luca-moser commented on packages/model/tangle/spent_db.go
> +// ReadLockSpentAddresses must be held while entering this function
```suggestion
// ReadLockSpentAddresses must be held while entering this function.
```

2020-01-08 09:33 UTC, luca-moser commented on packages/model/tangle/spent_db.go
> +// StreamSpentAddressesToWriter streams all spent addresses directly to an io.Writer
```suggestion
// StreamSpentAddressesToWriter streams all spent addresses directly to an io.Writer.
```

2020-01-08 09:33 UTC, luca-moser commented on packages/model/tangle/spent_db.go
> +// ReadLockSpentAddresses must be held while entering this function
```suggestion
// ReadLockSpentAddresses must be held while entering this function.
```

2020-01-08 09:33 UTC, luca-moser commented on plugins/snapshot/local_snapshot.go
> +		return fmt.Errorf("The snapshot target %d is too new. Should be older than %d", targetIndex, solidMilestoneIndex-SolidEntryPointCheckThresholdFuture)
Make an explicit ErrX var.

2020-01-08 09:33 UTC, luca-moser commented on plugins/snapshot/local_snapshot.go
> +		return fmt.Errorf("The snapshot target %d is too old. Should be newer than %d", targetIndex, snapshotInfo.SnapshotIndex)
Make an explicit ErrX var.

2020-01-08 09:33 UTC, luca-moser commented on plugins/snapshot/local_snapshot.go
> +		return fmt.Errorf("The snapshot target %d is too old. Should be newer than %d", targetIndex, snapshotInfo.PruningIndex+1+SolidEntryPointCheckThresholdPast)
Make an explicit ErrX var.

2020-01-08 09:33 UTC, luca-moser commented on plugins/snapshot/local_snapshot.go
> +	tangle.WriteUnlockSolidEntryPoints()
Make a defer after the line where you lock.

2020-01-08 09:33 UTC, luca-moser commented on plugins/snapshot/local_snapshot.go
> +		tangle.StoreSpentAddressesBytesInDatabase(batchEntries)
Handle error

2020-01-08 09:33 UTC, luca-moser commented on plugins/snapshot/plugin.go
> +	ErrNoSnapshotSpecified      = errors.New("No snapshot file was specified in the config")
```suggestion
	ErrNoSnapshotSpecified      = errors.New("no snapshot file was specified in the config")
```

2020-01-08 09:33 UTC, luca-moser commented on plugins/snapshot/plugin.go
> +					createLocalSnapshotWithoutLocking(solidMilestoneIndex-snapshotDepth, parameter.NodeConfig.GetString("localSnapshots.path"))
Handle error.

2020-01-08 09:33 UTC, luca-moser commented on plugins/snapshot/pruning.go
> +	tangle.DeleteApproversInDatabase(approvers)
Handler error.

2020-01-08 09:33 UTC, luca-moser commented on plugins/snapshot/pruning.go
> +	tangle.DeleteBundlesInDatabase(bundlesTxsToRemove)
Handler error.

2020-01-08 09:33 UTC, luca-moser commented on plugins/snapshot/pruning.go
> +	tangle.DeleteTransactionsInDatabase(txsToRemove)
Handler error.

2020-01-08 09:33 UTC, luca-moser commented on plugins/snapshot/pruning.go
> +	tangle.DeleteTransactionHashesForAddressesInDatabase(addresses)
Handler error.

2020-01-10 16:06 UTC, luca-moser submitted a review, later dismissed

2020-01-10 16:06 UTC, luca-moser commented on packages/model/tangle/ledger_db.go
> +		return errors.Wrap(NewDatabaseError(err), "failed to delete txs for addresses")
Wrong message.

2020-01-10 16:06 UTC, luca-moser commented on packages/model/tangle/ledger_db.go
> +		return errors.Wrap(NewDatabaseError(err), "failed to delete txs for addresses")
Wrong message.

2020-01-10 16:06 UTC, luca-moser commented on packages/model/tangle/milestones.go
> +		FixFirstSeenTxHashOperations(index)
Handle error

2020-01-10 16:06 UTC, luca-moser commented on packages/model/tangle/snapshot.go
> +		return nil, fmt.Errorf("Invalid length %d != 65", len(bytes))
Make an explicit error variable and use errors.Wrapf().

2020-01-10 16:06 UTC, luca-moser commented on packages/dag/helper.go
> +				return nil, fmt.Errorf("FindAllTails: Transaction not found: %v", txHash)
Make an explicit error variable and use errors.Wrapf().

2020-01-10 16:06 UTC, luca-moser commented on plugins/snapshot/global_snapshot.go
> +			return fmt.Errorf("Wrong format in %v", filePathLedger)
Make an explicit error variable and use errors.Wrapf().

2020-01-10 16:06 UTC, luca-moser commented on plugins/snapshot/global_snapshot.go
> +		return fmt.Errorf("ledgerEntries: %s", err)
Make an explicit error variable and use errors.Wrapf().

2020-01-10 16:06 UTC, luca-moser commented on plugins/snapshot/local_snapshot.go
> +		return fmt.Errorf(ErrTargetIndexTooNew.Error(), targetIndex, solidMilestoneIndex-SolidEntryPointCheckThresholdFuture)
Use the error variable, make a separate message and use errors.Wrapf() to retain the origin error variable.

2020-01-10 16:06 UTC, luca-moser commented on plugins/snapshot/local_snapshot.go
> +		return fmt.Errorf(ErrTargetIndexTooOld.Error(), targetIndex, snapshotInfo.SnapshotIndex)
Use the error variable, make a separate message and use errors.Wrapf() to retain the origin error variable.

2020-01-10 16:06 UTC, luca-moser commented on plugins/snapshot/local_snapshot.go
> +		return fmt.Errorf(ErrTargetIndexTooOld.Error(), targetIndex, snapshotInfo.PruningIndex+1+SolidEntryPointCheckThresholdPast)
Use the error variable, make a separate message and use errors.Wrapf() to retain the origin error variable.

2020-01-10 16:06 UTC, luca-moser commented on plugins/tangle/persisters.go
> +		if !transaction.IsRequested() {
Make a comment above this line explaining why requested transactions do not have have to be persisted in the firstSeenMilestone database. (obviously they should get confirmed, that's the reason, and therefore auto. be approvees of a milestone when pruning)

2020-01-10 18:27 UTC, IoTMOD approved these changes

2020-01-10 18:27 UTC, merged