Dust protection
iotaledger/hornet pull request #820
Opened 2021-01-12 02:28 UTC by alexsporn

This PR add dust protection as defined in the RFC and implemented in iota.go.

*Warning:* this changes the snapshot format to add the output type for each output.

**New:**

- Dust-validation during white-flag confirmation
- New conflict reason if transaction is ignored due to invalid dust allowance
- Dust allowance tracking is done in the UTXOManager with support for applying and rolling back whole confirmations diffs. This means that Dust is calculated properly when a node is started from a snapshot.

Note: the dust allowance tracking is done twice in this PR.
1. Inside the white-flag confirmation to be able to validate the semantics
2. After white-flag when applying the end-result of the white-flag confirmation.

Why?
- Temporary dust that exists between milestones is never booked into the ledger database.
- By having the UTXOManager calculate the dust internally we automatically gain the support for snapshots.

2021-01-12 23:16 UTC, muXxer requested changes

2021-01-12 23:16 UTC, muXxer commented on pkg/model/utxo/dust_db.go
> +	return u.readDustForAddress([]byte(address.String()))
this doesn't seem right to me, you are using the hex encode string instead of the address bytes here.

2021-01-12 23:16 UTC, muXxer commented on pkg/model/utxo/dust_db.go
> +		// Balance cannot be zero if there are no outputs
"be non-zero"

2021-01-12 23:16 UTC, muXxer commented on pkg/model/utxo/dust_db.go
> +	} else {
Why "else" here?
The former "if" already returns.

2021-01-12 23:16 UTC, muXxer commented on pkg/model/utxo/dust_db.go
> +	if dustAllowanceBalance == 0 {
If you delete if the count is 0, you could split up the former if:

```go

	if dustOutputCount == 0 {
		if dustAllowanceBalance != 0 {
			// Balance cannot be non-zero if there are no outputs
			return fmt.Errorf("%w: %s dustAllowanceBalance %d, dustOutputCount %d", ErrInvalidDustForAddress, hex.EncodeToString(addressBytes), dustAllowanceBalance, dustOutputCount)
		}

		// Remove from database
		return mutations.Delete(addressBytes)
	}
```

2021-01-12 23:16 UTC, muXxer commented on pkg/model/utxo/dust_db.go
> +	addressBytes := []byte(addressString)
Better call it `addressMapKey`

2021-01-12 23:16 UTC, muXxer commented on pkg/model/utxo/dust_db.go
> +			address := output.Address().String()
you should convert the address bytes to string, but the String function uses hex encoding

2021-01-12 23:16 UTC, muXxer commented on pkg/model/utxo/dust_db.go
> +			if found {
Can you move that "if" in the line above?

```go

			if diff, found := dustDiff[address]; found {
				diff.DustAllowanceBalanceDiff += int64(output.Amount())
			} else {
				dustDiff[address] = NewDustDiff(int64(output.Amount()), 0)
			}
```

2021-01-12 23:16 UTC, muXxer commented on pkg/model/utxo/dust_db.go
> +				diff, found := dustDiff[address]
Can you move that "if" in the line above?

2021-01-12 23:16 UTC, muXxer commented on pkg/model/utxo/dust_db.go
> +				address := output.Address().String()
you should convert the address bytes to string, but the String function uses hex encoding

2021-01-12 23:16 UTC, muXxer commented on pkg/model/utxo/dust_db.go
> +			address := output.Address().String()
you should convert the address bytes to string, but the String function uses hex encoding

2021-01-12 23:16 UTC, muXxer commented on pkg/model/utxo/dust_db.go
> +			if found {
Can you move that "if" in the line above?

2021-01-12 23:16 UTC, muXxer commented on pkg/model/utxo/dust_db.go
> +				if found {
Can you move that "if" in the line above?

2021-01-12 23:16 UTC, muXxer commented on pkg/model/utxo/dust_db.go
> +			if found {
Can you move that "if" in the line above?

2021-01-12 23:16 UTC, muXxer commented on pkg/model/utxo/dust_db.go
> +				if found {
Can you move that "if" in the line above?

2021-01-12 23:16 UTC, muXxer commented on pkg/model/utxo/dust_db.go
> +			if found {
Can you move that "if" in the line above?

2021-01-12 23:16 UTC, muXxer commented on pkg/model/utxo/dust_db.go
> +				if found {
Can you move that "if" in the line above?

2021-01-12 23:16 UTC, muXxer commented on pkg/model/utxo/dust_db.go
> +				address := output.Address().String()
you should convert the address bytes to string, but the String function uses hex encoding

2021-01-12 23:16 UTC, muXxer commented on pkg/model/utxo/dust_db.go
> +			address := output.Address().String()
you should convert the address bytes to string, but the String function uses hex encoding

2021-01-12 23:16 UTC, muXxer commented on pkg/model/utxo/dust_db.go
> +				address := output.Address().String()
you should convert the address bytes to string, but the String function uses hex encoding

2021-01-12 23:16 UTC, muXxer commented on pkg/model/utxo/dust_db.go
> +			address := output.Address().String()
you should convert the address bytes to string, but the String function uses hex encoding

2021-01-12 23:16 UTC, muXxer commented on pkg/model/utxo/dust_db.go
> +				address := output.Address().String()
you should convert the address bytes to string, but the String function uses hex encoding

2021-01-12 23:16 UTC, muXxer commented on pkg/model/utxo/dust_db.go
> +		if err := u.applyDustDiffForAddress(unspentOutput.Address().String(), int64(unspentOutput.Amount()), 0, dustMutations); err != nil {
you should convert the address bytes to string, but the String function uses hex encoding

2021-01-12 23:16 UTC, muXxer commented on pkg/model/utxo/dust_db.go
> +			if err := u.applyDustDiffForAddress(unspentOutput.Address().String(), 0, 1, dustMutations); err != nil {
you should convert the address bytes to string, but the String function uses hex encoding

2021-01-12 23:16 UTC, muXxer commented on pkg/whiteflag/white_flag.go
> +			if found {
Can you move that "if" in the line above?

2021-01-12 23:16 UTC, muXxer commented on pkg/whiteflag/white_flag.go
> +				if found {
Can you move that "if" in the line above?

2021-01-12 23:16 UTC, muXxer commented on pkg/whiteflag/white_flag.go
> +					if found {
Can you move that "if" in the line above?

2021-01-12 23:16 UTC, muXxer commented on pkg/whiteflag/white_flag.go
> +				if found {
Can you move that "if" in the line above?

2021-01-12 23:16 UTC, muXxer commented on pkg/whiteflag/white_flag.go
> +					if found {
Can you move that "if" in the line above?

2021-01-12 23:16 UTC, muXxer commented on pkg/whiteflag/white_flag.go
> +					address := output.Address().String()
you should convert the address bytes to string, but the String function uses hex encoding

2021-01-12 23:16 UTC, muXxer commented on pkg/whiteflag/white_flag.go
> +				address := output.Address().String()
you should convert the address bytes to string, but the String function uses hex encoding

2021-01-12 23:16 UTC, muXxer commented on pkg/whiteflag/white_flag.go
> +					address := input.Address().String()
you should convert the address bytes to string, but the String function uses hex encoding

2021-01-12 23:16 UTC, muXxer commented on pkg/whiteflag/white_flag.go
> +				address := input.Address().String()
you should convert the address bytes to string, but the String function uses hex encoding

2021-01-12 23:16 UTC, muXxer commented on pkg/whiteflag/white_flag.go
> +			dustDiff, found := wfConf.dustDiff[address.String()]
you should convert the address bytes to string, but the String function uses hex encoding

2021-01-14 21:32 UTC, muXxer requested changes

2021-01-14 21:32 UTC, muXxer commented on pkg/whiteflag/confirmation.go
> +			meta.GetMetadata().SetMilestone(true)
This way we would only mark the first message with the milestone payload we receive as milestone.
This could differ from node to node. But I don't know how to avoid it :/

2021-01-14 21:32 UTC, muXxer commented on pkg/whiteflag/white_flag.go
> +	// Contains the Dust allowance diff for the given addresses.
is "for the given address" correct in this context?

2021-01-14 21:32 UTC, muXxer commented on pkg/model/utxo/dust.go
> +			addressKey := output.Address().String()
this seems wrong

2021-01-14 21:32 UTC, muXxer commented on pkg/model/utxo/dust.go
> +				addressKey := output.Address().String()
this seems wrong

2021-01-16 10:17 UTC, alexsporn commented on pkg/whiteflag/confirmation.go
> +			meta.GetMetadata().SetMilestone(true)
Yeah, but it is the one we actually used to process the milestone for this node, so better than nothing 🤷

2021-01-16 20:05 UTC, alexsporn commented
This needs https://github.com/iotaledger/iota.go/pull/238 to be merged first and go.mod updated

2021-01-17 15:13 UTC, muXxer approved these changes

2021-01-17 15:45 UTC, muXxer approved these changes

2021-01-17 17:26 UTC, merged